export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const LOADING_RESTAURANT = 'LOADING_RESTAURANT';